export const properties = [
    {
      id: 1,
      slug: "luxury-villa",
      title: "Luxury Villa",
      location: "Los Angeles",
      price: 1200000,
      image: ["/Gon5.jpg","/Gon5.jpg","/Gon5.jpg","/Gon5.jpg"],
      bedrooms: 2,
      bathrooms: 4,
      parking: 1,
      garages:0,
      type: "Villa",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 2,
      slug: "city-apartment",
      title: "City Apartment",
      location: "Sabo Yaba",
      price: 80000000,
      image: ["/Gon10.jpg","/Gon10.jpg","/Gon10.jpg","/gow4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 3,
      slug: "abuja-house",
      title: "Abuja house",
      location: "Lagos, Nigeria",
      price: 50000000,
      image: ["/Gon7.jpg","/Gon7.jpg","/Gon7.jpg","/Gon7.jpg"],
      bedrooms: 3,
      bathrooms: 2,
      parking: 2,
      garages: 0,
      type: "villa",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 4,
      slug: "asaba-golden-garden",
      title: "Asaba Golden garden",
      location: "Delta, Nigeria",
      price: 850000000,
      image: ["/Gon8.jpg","/Gon8.jpg","/Gon8.jpg","/Gon8.jpg"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Rental",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 5,
      slug: "paint-house",
      title: "Paint House",
      location: "Abia",
      price: 95000000,
      image: ["/Gon9.jpg","/Gon9.jpg","/Gon9.jpg","/Gon9.jpg"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Accomodation",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 6,
      slug: "12-archars-of-land",
      title: "12 Archars of land",
      location: "Mowe Ibafo",
      price: 850000,
      image: ["/gon1.jpg","/gon2.jpg","/gon3.jpg","/gon4.jpg"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Lands",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 7,
      slug: "20-unit-rooms-for-rent",
      title: "20 unit rooms for rent",
      location: "Ajao Estate",
      price: 2050000,
      image: ["/gon3.jpg","/gon3.jpg","/gon3.jpg","/gon3.jpg"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Rooms",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 8,
      slug: "city-apartment",
      title: "City Apartment",
      location: "Victoria Island",
      price: 3050000,
      image: ["/Gon4.png","/Gon4.png","/Gon4.png","/Gon4.png"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 9,
      slug: "River-apartment",
      title: "5 Bedrom Ditach Apartment",
      location: "Mary Land",
      price: 20050000,
      image: ["/Gon12.jpg","/Gon12.jpg","/Gon12.jpg","/Gon12.jpg"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 10,
      slug: "city-House",
      title: "4 Duplex Apartment",
      location: "Apapa",
      price: 950000000,
      image: ["/Gon19.jpg","/Gon19.jpg","/Gon19.jpg","/Gon19.jpg"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    {
      id: 11,
      slug: "Ireland-apartment",
      title: "Castle Apartment",
      location: "Ireland",
      price: 200000000,
      image: ["/Gon20.jpg","/Gon20.jpg","/Gon20.jpg","/Gon20.jpg"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },

{
      id: 12,
      slug: "Lagos-apartment",
      title: "Big 5 BedRoom Apartment",
      location: "Ajah,Lagos",
      price: 850000000,
      image: ["/Gon21.jpg","/Gon21.jpg","/Gon21.jpg","/Gon21.jpg"],
      bedrooms: 6,
      bathrooms: 2,
      parking: 1,
      garages: 0,
      type: "Apartment",
      year: 2024,
      description: "this is a very good property"
    },
    // Add more properties...

  ];
  